//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalDb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class entrymodel
    {
        public int EntryId { get; set; }
        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Beneficiary First Name")]
        public string Beneficiary_First_Name { get; set; }

        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Beneficiary Middle Name")]
        public string Beneficiary_Middle_Name { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Beneficiary Last Name")]
        public string Beneficiary_Last_Name { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Principal First Name")]
        public string Principal_First_Name { get; set; }

        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Principal Middle Name")]
        public string Principal_Middle_Name { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Principal Last Name")]
        public string Principal_Last_Name { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [Display(Name = "Date Of Birth")]
        public string DOB { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Marital Status")]
        public int maritalstatus_id { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Visa Category")]
        public int visacategory_id { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Passport Number")]
        public string Passport_Number { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Category")]
        public string Category { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Nationality")]
        public string Nationality { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Gender")]
        public int gender_id { get; set; }

        [Required]
        [Display(Name = "Relationship")]
        public int Rid { get; set; }

        [Required]
        [Display(Name = "Gross Salary")]
        public int Sid { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Emirates ID")]
        public string Emirates_ID { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "City Of Residence")]
        public string City_of_Residence { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Company Name")]
        public string Company_Name { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "UID Number")]
        public string UID_Number { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "SubGroup Name")]
        public string SubGroup_Name { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Emirates Of Visa")]
        public string Emirates_Of_Visa { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Work Location")]
        public string Work_Location { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Entity Id")]
        public string Entity_Id { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Entity Type")]
        public string Entity_Type { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Establishment Id")]
        public string Establishment_Id { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Insurance Company Name")]
        public string insurance_companyname { get; set; }

        [Required]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        [Display(Name = "Policy Number")]
        public string policy { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        public string PhoneNumber { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Photo")]
        public string photo { get; set; }

        [Display(Name = "Visa")]
        public string Visa { get; set; }

        [Display(Name = "Passport Copy")]
        public string passport_copy { get; set; }

        [Display(Name = "Emirates ID Copy")]
        public string Emirates_id_copy { get; set; }

        [Display(Name = "Medical Card")]
        public string medical_card { get; set; }

        [Display(Name = "Other Documents")]
        public string other_documents { get; set; }

        [Display(Name = "Date Time")]
        public string Date_Time { get; set; }

        [Display(Name = "other_field_1", ResourceType = typeof(medicaldb))]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        public string other_field_1 { get; set; }

        [Display(Name = "other_field_2", ResourceType = typeof(medicaldb))]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        public string other_field_2 { get; set; }

        [Display(Name = "other_field_3", ResourceType = typeof(medicaldb))]
        [ScaffoldColumn(true)]
        [DataType(DataType.Text)]
        public string other_field_3 { get; set; }

    
        public virtual gender gender { get; set; }
        public virtual grosssalary grosssalary { get; set; }
        public virtual marital_status marital_status { get; set; }
        public virtual relationship relationship { get; set; }
        public virtual visa_category visa_category { get; set; }
    }
}
