//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalDb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medicaldbEntities : DbContext
    {
        public medicaldbEntities()
            : base("name=medicaldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<entrymodel> entrymodels { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<grosssalary> grosssalaries { get; set; }
        public virtual DbSet<marital_status> marital_status { get; set; }
        public virtual DbSet<relationship> relationships { get; set; }
        public virtual DbSet<visa_category> visa_category { get; set; }
    }
}
